id: P0163
name: ModifiesSecuritySettings
signature: 'ModifiesSecuritySettings(f: File) -> Bool'
category: Runtime/PrivilegeBoundary
description: Disables Defender/Firewall. **Set** on registry/PowerShell cmdlets.
scope:
  object: file
  format: generic
mitre_attack: [T1562.001]
trigger_logic:
  positive:
  - keywords:
    - Disables
    - Defender
    - Firewall.
    - registry
  negative:
thresholds: {}
confidence_rules:
  - rule: primary_evidence
    weight: 1.0
evidence_binding:
  captures:
  - bytespan: O(0..512)
extraction:
  method: DynamicMonitoring
  failure_modes: []
false_positives: []
false_negatives: []
provenance:
  citations:
  - ref: C024  # 'Process Injection (T1055)'
  author: '@gview-team'
implementation:
  status: planned
  perf_cost: medium
version: 1
