id: P0186
name: EncryptsConfiguration
signature: 'EncryptsConfiguration(f: File) -> Bool'
category: Hybrid/AntiAnalysisEvasion
description: Config blob encrypted. **Set** if decrypted at runtime or high-entropy config detected.
scope:
  object: file
  format: generic
mitre_attack: [T1562]
trigger_logic:
  positive:
  - keywords:
    - Config
    - blob
    - encrypted.
    - decrypted
  negative:
thresholds: {}
confidence_rules:
  - rule: primary_evidence
    weight: 1.0
evidence_binding:
  captures:
  - bytespan: O(0..512)
extraction:
  method: Hybrid
  failure_modes: []
false_positives: []
false_negatives: []
provenance:
  citations:
  - ref: C022  # 'Ten process injection techniques: survey of common and trending techniques'
  author: '@gview-team'
implementation:
  status: planned
  perf_cost: medium
version: 1
