id: I0102
name: StealthconfigloaderToIssuspiciousFinalHigh
signature: (AntiAnalysisStack(f) ∨ StealthConfigLoader(f)) ∧ BeaconingPattern(f) →
  IsSuspicious(f) {Final, high}
category: Behavioral/AntiAnalysis
scope:
  object: file
  postconditions:
  - Flag: IsSuspicious(f) {Final, high}
description: When (AntiAnalysisStack(f) ∨ StealthConfigLoader(f)) ∧ BeaconingPattern(f)
  holds, assert IsSuspicious(f) {Final, high}.
trigger_logic:
  antecedent:
  - (AntiAnalysisStack(f) ∨ StealthConfigLoader(f))=true
  - BeaconingPattern(f)=true
  consequent:
  - IsSuspicious(f) {Final, high}=true
evidence_binding:
  requires:
  - artifact: anti_vm
    fields:
    - registry_keys
    - drivers
    - timing
  - artifact: process_tree
    fields:
    - ppid_spoofing
    - unhooks
  retention_hint: Store ±120s around key triggering events.
confidence:
  base: 0.6
  modifiers:
  - 'if Periodicity jitter < 10%: +0.05'
  calibration: isotonic_2025_09
severity:
  level: info
  rationale: Derived from rule tier and observed behaviors.
conflict_handling:
  contradicts:
  - 'Rule: R-1980 ''BenignAutoUpdate'''
  resolution: Prefer higher confidence unless allowlist(domain or signer) applies.
adversary_evasion:
  known_bypasses: []
  mitigations: []
provenance:
  citations:
  - id: C036
  author: '@gview-team'
implementation:
  status: planned
  perf_cost: low
version: 1
